name: deploy-release

# on:
#   pull_request:
#     types:
#       - "closed"

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    if:  startsWith(github.head_ref, 'release-please')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was ${{github.head_ref}} deployed