name: deploy-release

on:
  push:
    branches:
      - 'releases/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
              Deploy done!!!