name: release-please

on: 
  push:
   branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
        release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: release please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
          package-name: gh-release-sample
      - run: |
          echo ${{ steps.release.outputs.release_created }}

      - name: deploy
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo Deployed!

      - name: Dispatch Release Created
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.actions  }}
          repository: martinsaporiti/gh-release-sample
          event-type: release-created
          client-payload: '{}'